_target_: src.models.wificsi_module.WiFiCSIModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 1e-3
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.models.components.simple_net.SimpleNet
  in_channels: 30
  conv_h1_channels: 30
  conv_h2_channels: 10
  conv_h3_channels: 1
  linear_h1_size: 64
  output_size: 7